# Generated by Django 3.1.2 on 2020-10-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('attractions', '0001_initial'),
        ('comment_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('approvedd', models.BooleanField()),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.adress')),
                ('attractions', models.ManyToManyField(to='attractions.Attraction')),
                ('comments', models.ManyToManyField(to='comment_reviews.Comment')),
                ('reviews', models.ManyToManyField(to='comment_reviews.Review')),
            ],
        ),
    ]
