# Generated by Django 3.1.2 on 2020-10-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots', '0002_auto_20201013_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='approvedd',
            field=models.BooleanField(default=True),
        ),
    ]
